// Location data - Slovenia and Northern Italy nature trails
const locations = [
    // Slovenia trails
    {
        id: 1,
        name: 'Vintgar Gorge',
        lat: 46.3778,
        lng: 14.0556,
        distance: '4.2km',
        duration: '1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'slovenia',
        description: 'Suspended boardwalk winding along emerald green waters, Šum waterfall is absolutely stunning! One-way trail design, remember to book tickets online in advance. 🚗 Parking is first-come-first-served (P1-P6 are closer).'
    },
    {
        id: 2,
        name: 'Casparin Trail',
        lat: 46.2500,
        lng: 13.9500,
        distance: '5.1km',
        duration: '1.5h',
        bestSeason: 'Best: Jul-Sep',
        region: 'slovenia',
        description: 'Through neighborhoods, then gravel and rocky paths! Moderate difficulty trail, but wet sections can be slippery. Entrance and summit café only accept cash, remember to bring some.'
    },
    {
        id: 3,
        name: 'Slemenova Špica',
        lat: 46.4167,
        lng: 13.7500,
        distance: '5.6km',
        duration: '2.7h',
        bestSeason: 'Best: Jul-Oct',
        region: 'slovenia',
        description: 'Starting from Vršič Pass, summit viewpoint of the Julian Alps, overlooking layered mountain ranges! More suitable for experienced hikers, beginners should bring proper gear.'
    },
    {
        id: 4,
        name: 'Lake Bled via Bled City Center',
        lat: 46.3683,
        lng: 14.0883,
        distance: '6.3km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: 'Lakeside hike + castle visit in one go! Forest paths can be slippery in rain, but the views are absolutely worth it 😭 You can take a boat to the island, and explore Bled town along the way.'
    },
    {
        id: 5,
        name: 'Mount Visevnik',
        lat: 46.3000,
        lng: 14.1000,
        distance: '8.2km',
        duration: '3.2h',
        bestSeason: 'Best: Jun-Oct',
        region: 'slovenia',
        description: 'Stunning mountain views in summer, transforms into ski slopes in winter! Counter-clockwise route is easier, loose rocks on uphill and downhill sections, trekking poles are essential ✅'
    },
    {
        id: 6,
        name: 'Mostnica Gorge - Voje Waterfall',
        lat: 46.3500,
        lng: 13.9000,
        distance: '10.5km',
        duration: '4h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: 'Traverse narrow gorges, water so emerald green it glows! Restaurant before the waterfall at the end, perfect spot for a coffee break.'
    },
    {
        id: 7,
        name: 'Velika Planina Loop',
        lat: 46.2833,
        lng: 14.6167,
        distance: '12.6km',
        duration: '4.5h',
        bestSeason: 'Best: Jul-Aug',
        region: 'slovenia',
        description: 'Hidden gem route known only to locals! Initial climb is a bit tiring, but summer peaks 🏔️ feature wildflowers and grazing cattle, perfect for photos.'
    },
    {
        id: 8,
        name: '7-Lake Hike from Planina Blato',
        lat: 46.2833,
        lng: 13.8167,
        distance: '18.7km',
        duration: '6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'slovenia',
        description: 'Crossing Triglav National Park, passing 7 alpine lakes! Water so clear you can see fish, rich landscapes of forests + rocky mountains.'
    },
    {
        id: 9,
        name: 'Alpe Adria Trail: Trenta - Bovec',
        lat: 46.3333,
        lng: 13.5833,
        distance: '21.4km',
        duration: '7h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: 'Following the emerald Soča River, through pristine national park, suspension bridges crossing gorges are thrilling! Well-marked trail, fishing possible along the way.'
    },
    {
        id: 10,
        name: 'Valley of The Seven Lakes',
        lat: 46.2667,
        lng: 13.8333,
        distance: '24.5km',
        duration: '9.2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'slovenia',
        description: 'Summer blooms with alpine wildflowers, might even spot marmots! Some sections have many rocks, wear grippy shoes! Mountain huts available for rest along the way, check official website for opening hours.'
    },
    // Northern Italy trails
    {
        id: 11,
        name: 'Bellagio – Pescallo Loop',
        lat: 45.9886,
        lng: 9.2603,
        distance: '4.5km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: 'Mixed lakeshore and hillside route with constantly changing perspectives, overlooking Lake Como\'s classic "Y-shaped" lake surface. Best light in early morning or evening, relatively fewer crowds.'
    },
    {
        id: 12,
        name: 'Varenna – Sentiero del Viandante',
        lat: 46.0100,
        lng: 9.2833,
        distance: '6.8km',
        duration: '2.5h',
        bestSeason: 'Best: Apr-Jun / Sep-Oct',
        region: 'italy',
        description: 'Medieval pilgrimage-level hiking route, alternating between stone paths, olive groves, and lakeside villages. Strong historical atmosphere, perfect for slow-paced walking.'
    },
    {
        id: 13,
        name: 'Greenway del Lago di Como',
        lat: 45.9833,
        lng: 9.2667,
        distance: '10km',
        duration: '3-4h',
        bestSeason: 'Year-round',
        region: 'italy',
        description: 'Gentle trail connecting multiple lakeside towns, can be done in sections. Features gardens, villas, and lake views throughout, perfect for "no-technical-pressure" scenic walking.'
    },
    {
        id: 14,
        name: 'Sirmione Peninsula Walk',
        lat: 45.4917,
        lng: 10.6083,
        distance: '5.2km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'italy',
        description: 'Walk along the peninsula to the Grotte di Catullo ruins at the end. Crystal clear waters, excellent combination of ruins and nature. Windy but with open vistas.'
    },
    {
        id: 15,
        name: 'Monte Baldo Panorama Trail',
        lat: 45.7167,
        lng: 10.8500,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'italy',
        description: 'Cable car directly to 1700m elevation, ridge hiking overlooking the entire Lake Garda. Alpine meadows + large-scale lake views, quite windy, dress warmly.'
    },
    {
        id: 16,
        name: 'Riva del Garda – Ponale Path',
        lat: 45.8833,
        lng: 10.8500,
        distance: '8km',
        duration: '2.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: 'Classic cliffside lake route, gravel path but low technical difficulty. Lake water color changes are very noticeable, photography-friendly.'
    },
    {
        id: 17,
        name: 'Isola Bella & Stresa Lakeside Walk',
        lat: 45.8833,
        lng: 8.5333,
        distance: '4km',
        duration: '1-1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: 'Lakeside walk + island garden combination, clear boundary between man-made and natural. Overall atmosphere is elegant and quiet.'
    },
    {
        id: 18,
        name: 'Monte Isola Loop',
        lat: 45.7167,
        lng: 10.0833,
        distance: '9km',
        duration: '3h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: 'Hiking around the lake\'s central island, almost no motor vehicles, very small village scale, strong local life atmosphere. One of the least "over-touristed" spots in the lake region.'
    },
    // Dolomites trails
    {
        id: 19,
        name: 'Tre Cime di Lavaredo Loop',
        lat: 46.6189,
        lng: 12.3025,
        distance: '10.2km',
        duration: '3-4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'The most iconic limestone peaks of the Dolomites, mature loop trail with clear signage. Experience vertical rock walls and scree slopes up close, windy with strong sun exposure, remember sun protection.'
    },
    {
        id: 20,
        name: 'Lago di Braies',
        lat: 46.6942,
        lng: 12.0847,
        distance: '3.6km',
        duration: '1-1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'dolomites',
        description: 'Turquoise blue lake + coniferous forests + cliff reflections, fewest people in early morning. Can walk around the lake or stop briefly for photos, heavily commercialized but visually stunning.'
    },
    {
        id: 21,
        name: 'Seceda Ridgeline',
        lat: 46.5500,
        lng: 11.7000,
        distance: '6.5km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'Cable car directly to elevation, walking along knife-edge grassy slopes with extreme depth perception. Exposed path but not technically difficult, weather changes quickly, check cloud coverage.'
    },
    {
        id: 22,
        name: 'Alpe di Siusi Loop',
        lat: 46.5333,
        lng: 11.6667,
        distance: '12km',
        duration: '4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'Europe\'s largest alpine meadow, gentle rolling highland with jagged rock peaks in the distance. Perfect for slow walking, photography, and relaxation, cattle everywhere in summer.'
    },
    {
        id: 23,
        name: 'Passo Giau – Mondeval Walk',
        lat: 46.4833,
        lng: 12.0500,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'Starting from the pass with panoramic views, layered ridges create an extremely enclosed feeling. Light changes are very dramatic, especially stunning during sunset hours.'
    },
    {
        id: 24,
        name: 'Cinque Torri',
        lat: 46.5167,
        lng: 12.0500,
        distance: '5.4km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'Massive rock towers standing in grassy slopes, WWI ruins scattered throughout. Short route but strong spatial tension, perfect for half-day trip.'
    },
    {
        id: 25,
        name: 'Val di Funes – Odle Panorama Trail',
        lat: 46.6500,
        lng: 11.6833,
        distance: '7.8km',
        duration: '2.5-3h',
        bestSeason: 'Best: May-Oct',
        region: 'dolomites',
        description: 'Classic "church + spires" picture valley, beautiful proportions of pastures and rock walls. Quiet villages, overall very slow-paced.'
    },
    {
        id: 26,
        name: 'Lago di Sorapis',
        lat: 46.5500,
        lng: 12.2167,
        distance: '11km',
        duration: '4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: 'Destination is a milky blue glacial lake, color is extremely unreal. Some sections have steel cable assistance, small exposed sections but not technical, slippery after rain.'
    },
    // Swiss Alps trails
    {
        id: 27,
        name: 'Five Lakes Walk',
        lat: 46.0167,
        lng: 7.7500,
        distance: '9.8km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: 'Classic Matterhorn viewpoint route, connecting 5 alpine lakes, can see snow peak reflections on sunny days. Overall low difficulty, but high tourist density.'
    },
    {
        id: 28,
        name: 'Gornergrat Panorama Trail',
        lat: 45.9833,
        lng: 7.7833,
        distance: '6.3km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: 'Mountain train directly to viewing ridge, overlooking glaciers and multiple 4000m+ snow peaks. Grand vistas, almost entirely "being watched".'
    },
    {
        id: 29,
        name: 'Grindelwald First – Bachalpsee',
        lat: 46.6500,
        lng: 8.0333,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: 'Alpine lake + meadow combination, mature path with strong sense of safety. Lake reflections are very stable in good weather, clear photography spots.'
    },
    {
        id: 30,
        name: 'Eiger Trail',
        lat: 46.5833,
        lng: 8.0000,
        distance: '6.5km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: 'Walking along the Eiger north face, vertical rock walls create extreme sense of oppression. Path is clear but psychological scale is large, suitable for those not afraid of heights.'
    },
    {
        id: 31,
        name: 'Oeschinensee Panorama Loop',
        lat: 46.5000,
        lng: 7.7167,
        distance: '7km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: 'Glacial lake with deep blue color, strong sense of enclosure from lake shore and high rock walls. Can do short hike or loop around lake, perfect for a slower-paced day.'
    },
    {
        id: 32,
        name: 'Aletsch Glacier Viewpoint Trail',
        lat: 46.3833,
        lng: 8.0167,
        distance: '8-10km',
        duration: '3-4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: 'Overlooking Europe\'s largest glacier, scale is extremely grand. Route itself is not difficult, but the "human-geology" contrast is very direct.'
    },
    {
        id: 33,
        name: 'Mürren – Grütschalp Walk',
        lat: 46.5667,
        lng: 7.9000,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: 'High-altitude trail along cliff edge, facing Schilthorn peak group. Villages, waterfalls, and mountain walls form extremely stable scenic composition.'
    },
    {
        id: 34,
        name: 'Schynige Platte Panorama Trail',
        lat: 46.6500,
        lng: 7.8500,
        distance: '5.6km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: 'Alpine plants + distant lake views, can see both Lake Thun and Lake Brienz simultaneously. High plant diversity, relaxed pace.'
    },
    {
        id: 35,
        name: 'Val Bregaglia – Soglio Walk',
        lat: 46.3333,
        lng: 9.5333,
        distance: '6-8km',
        duration: '2.5-3h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: 'From stone-built mountain village into valley hiking, scale suddenly tightens. Few people, weak commercial feel, more "lived-in Alps" atmosphere.'
    },
    {
        id: 36,
        name: 'Engadin Lakes Trail',
        lat: 46.4833,
        lng: 9.8333,
        distance: '11km',
        duration: '3.5h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: 'Connecting multiple highland lakes, clean light and gentle terrain. Overall atmosphere is rational and restrained, "highly managed nature".'
    },
    // Austrian Alps trails
    {
        id: 37,
        name: 'Hallstatt – Dachstein Panorama Walk',
        lat: 47.5622,
        lng: 13.6492,
        distance: '5.5km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: 'Lake, salt mining town, and steep mountain walls layered in the same frame, extremely high landscape density. Clearly commercialized, but terrain and scale are very typical.'
    },
    {
        id: 38,
        name: 'Gosausee Loop',
        lat: 47.5333,
        lng: 13.5167,
        distance: '4.5km',
        duration: '1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: 'Crystal clear lake, can see Dachstein glacier reflections on sunny days. Short loop route but visually complete, perfect as a lightweight nature spot.'
    },
    {
        id: 39,
        name: 'Salzkammergut Lakes Trail',
        lat: 47.7000,
        lng: 13.6167,
        distance: '8-12km',
        duration: '3-4h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: 'Lakes and forests alternating, gentle slopes, overall slow pace. "Livable Alps", more about living atmosphere than wilderness.'
    },
    {
        id: 40,
        name: 'Krimml Waterfalls Path',
        lat: 47.2167,
        lng: 12.1833,
        distance: '4km',
        duration: '2h',
        bestSeason: 'Best: May-Sep',
        region: 'austria',
        description: 'Europe\'s highest drop waterfall group, extremely high water volume, sound and humidity have strong presence. One of Austria\'s most "natural power display" routes.'
    },
    {
        id: 41,
        name: 'Grossglockner High Alpine Road Walks',
        lat: 47.0833,
        lng: 12.8333,
        distance: '6-10km',
        duration: '2-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: 'Short hiking combinations along high alpine road, can observe glaciers and bare rock up close. Grand natural scale, but clear sense of human intervention.'
    },
    {
        id: 42,
        name: 'Zell am See – Schmittenhöhe Trail',
        lat: 47.3167,
        lng: 12.8000,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'austria',
        description: 'Clear perspective shifts between lake and hillside, overlooking Zell am See panorama. Perfect for flexible itinerary when weather is unstable.'
    },
    {
        id: 43,
        name: 'Hohe Tauern National Park Trail',
        lat: 47.1667,
        lng: 12.5000,
        distance: '10-15km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: 'Austria\'s largest national park, glaciers, wetlands, and wide valleys coexist. Open space, relatively less human intervention, closer to "ecological Alps".'
    },
    {
        id: 44,
        name: 'Rax Plateau Loop',
        lat: 47.7000,
        lng: 15.7000,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: 'Highland plateau terrain, meadows and rock walls suddenly unfold. Perfect for short trips from city into mountains, low technical hiking requirements.'
    },
    {
        id: 45,
        name: 'Hochschwab Plateau Hike',
        lat: 47.6167,
        lng: 15.1500,
        distance: '12-18km',
        duration: '5-6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: 'Massive limestone plateau, open space with strong sense of direction. Few people, sparse trail markers, more suitable for experienced hikers.'
    },
    {
        id: 46,
        name: 'Wilder Kaiser Mountains Loop',
        lat: 47.5500,
        lng: 12.3000,
        distance: '9-13km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: 'Area where steep rock walls and pastures coexist, very three-dimensional mountain mass. More "substantial" than Dolomites, but less dramatic composition.'
    },
    // French Alps trails
    {
        id: 47,
        name: 'Lac Blanc',
        lat: 45.9833,
        lng: 6.8667,
        distance: '6km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: 'Classic alpine lake route overlooking Mont Blanc massif, lake surface can reflect snow peak outlines on sunny days. Many tourists, but composition is extremely stable.'
    },
    {
        id: 48,
        name: 'Grand Balcon Nord',
        lat: 45.9167,
        lng: 6.8667,
        distance: '7.5km',
        duration: '3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'france',
        description: 'Traversing Chamonix valley along mountainside, facing complete Mont Blanc massif. Mature route with moderate slopes, a "precisely designed viewing trail".'
    },
    {
        id: 49,
        name: 'Mer de Glace Viewpoint Walk',
        lat: 45.9333,
        lng: 6.9167,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'france',
        description: 'Close-up view of geological structures after glacier retreat, extremely strong contrast. Not "beautiful", but direct sense of time and scale.'
    },
    {
        id: 50,
        name: 'Aiguille du Midi Ridge Area',
        lat: 45.9000,
        lng: 6.8833,
        distance: '3-4km',
        duration: '1-1.5h',
        bestSeason: 'Year-round (weather dependent)',
        region: 'france',
        description: 'Cable car directly to 3800m elevation, extreme vertical sense and exposed views coexist. More of an experience point than a complete hike.'
    },
    {
        id: 51,
        name: 'Lake Annecy – Talloires Walk',
        lat: 45.8500,
        lng: 6.1667,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: Apr-Oct',
        region: 'france',
        description: 'Lakeshore and hillside parallel, water body and city boundaries very clear. Overall atmosphere closer to "livable landscape" than pure alpine.'
    },
    {
        id: 52,
        name: 'Vanoise National Park Trail',
        lat: 45.3333,
        lng: 6.8333,
        distance: '10-15km',
        duration: '4-6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: 'One of France\'s earliest national parks, glacial valleys and alpine pastures coexist. Wilder than Switzerland, less facilities than Austria.'
    },
    {
        id: 53,
        name: 'Queyras Regional Nature Park Loop',
        lat: 44.7000,
        lng: 6.8000,
        distance: '9-12km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: 'High mountain area near Italian border, few people, dry terrain. Colors lean gray-green, overall more rough and marginal.'
    },
    {
        id: 54,
        name: 'Val d\'Isère Alpine Meadow Walk',
        lat: 45.4500,
        lng: 6.9833,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: 'Ski area transforms into alpine meadows in summer, open and gently rolling. Typical example of "functional mountain" converted to hiking space.'
    }
];