// Location data organized by series
const seriesData = {
    alpine: [
    // Slovenia trails
    {
        id: 1,
        name: 'Vintgar Gorge',
        lat: 46.3778,
        lng: 14.0556,
        distance: '4.2km',
        duration: '1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'slovenia',
        description: '悬空栈道沿着翠绿色的水流蜿蜒，Šum瀑布绝对令人惊叹！单向步道设计，记得提前在线预订门票。🚗 停车位先到先得（P1-P6更近）。| Suspended boardwalk winding along emerald green waters, Šum waterfall is absolutely stunning! One-way trail design, remember to book tickets online in advance. 🚗 Parking is first-come-first-served (P1-P6 are closer).'
    },
    {
        id: 2,
        name: 'Casparin Trail',
        lat: 46.2500,
        lng: 13.9500,
        distance: '5.1km',
        duration: '1.5h',
        bestSeason: 'Best: Jul-Sep',
        region: 'slovenia',
        description: '穿过居民区，然后是碎石和岩石小径！中等难度步道，但潮湿路段可能很滑。入口和山顶咖啡馆只接受现金，记得带一些。| Through neighborhoods, then gravel and rocky paths! Moderate difficulty trail, but wet sections can be slippery. Entrance and summit café only accept cash, remember to bring some.'
    },
    {
        id: 3,
        name: 'Slemenova Špica',
        lat: 46.4167,
        lng: 13.7500,
        distance: '5.6km',
        duration: '2.7h',
        bestSeason: 'Best: Jul-Oct',
        region: 'slovenia',
        description: '从弗尔希奇山口出发，朱利安阿尔卑斯山的山顶观景点，俯瞰层叠的山脉！更适合有经验的徒步者，初学者应携带合适的装备。| Starting from Vršič Pass, summit viewpoint of the Julian Alps, overlooking layered mountain ranges! More suitable for experienced hikers, beginners should bring proper gear.'
    },
    {
        id: 4,
        name: 'Lake Bled via Bled City Center',
        lat: 46.3683,
        lng: 14.0883,
        distance: '6.3km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: '湖边徒步+城堡参观一次完成！森林小径在雨天可能很滑，但景色绝对值得 😭 可以乘船到岛上，沿途探索布莱德小镇。| Lakeside hike + castle visit in one go! Forest paths can be slippery in rain, but the views are absolutely worth it 😭 You can take a boat to the island, and explore Bled town along the way.'
    },
    {
        id: 5,
        name: 'Mount Visevnik',
        lat: 46.3000,
        lng: 14.1000,
        distance: '8.2km',
        duration: '3.2h',
        bestSeason: 'Best: Jun-Oct',
        region: 'slovenia',
        description: '夏季山景壮丽，冬季变成滑雪坡道！逆时针路线更容易，上下坡路段有松散的岩石，登山杖是必需的 ✅ | Stunning mountain views in summer, transforms into ski slopes in winter! Counter-clockwise route is easier, loose rocks on uphill and downhill sections, trekking poles are essential ✅'
    },
    {
        id: 6,
        name: 'Mostnica Gorge - Voje Waterfall',
        lat: 46.3500,
        lng: 13.9000,
        distance: '10.5km',
        duration: '4h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: '穿越狭窄的峡谷，水色翠绿如发光！瀑布前的餐厅，是休息喝咖啡的完美地点。| Traverse narrow gorges, water so emerald green it glows! Restaurant before the waterfall at the end, perfect spot for a coffee break.'
    },
    {
        id: 7,
        name: 'Velika Planina Loop',
        lat: 46.2833,
        lng: 14.6167,
        distance: '12.6km',
        duration: '4.5h',
        bestSeason: 'Best: Jul-Aug',
        region: 'slovenia',
        description: '只有当地人才知道的隐藏宝藏路线！初始爬升有点累，但夏季的山峰 🏔️ 有野花和放牧的牛群，非常适合拍照。| Hidden gem route known only to locals! Initial climb is a bit tiring, but summer peaks 🏔️ feature wildflowers and grazing cattle, perfect for photos.'
    },
    {
        id: 8,
        name: '7-Lake Hike from Planina Blato',
        lat: 46.2833,
        lng: 13.8167,
        distance: '18.7km',
        duration: '6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'slovenia',
        description: '穿越特里格拉夫国家公园，经过7个高山湖泊！水清澈见底，可以看到鱼，丰富的森林+岩石山地景观。| Crossing Triglav National Park, passing 7 alpine lakes! Water so clear you can see fish, rich landscapes of forests + rocky mountains.'
    },
    {
        id: 9,
        name: 'Alpe Adria Trail: Trenta - Bovec',
        lat: 46.3333,
        lng: 13.5833,
        distance: '21.4km',
        duration: '7h',
        bestSeason: 'Year-round',
        region: 'slovenia',
        description: '沿着翠绿色的索查河，穿过原始的国家公园，跨越峡谷的悬索桥令人兴奋！路标清晰，沿途可以钓鱼。| Following the emerald Soča River, through pristine national park, suspension bridges crossing gorges are thrilling! Well-marked trail, fishing possible along the way.'
    },
    {
        id: 10,
        name: 'Valley of The Seven Lakes',
        lat: 46.2667,
        lng: 13.8333,
        distance: '24.5km',
        duration: '9.2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'slovenia',
        description: '夏季盛开着高山野花，甚至可能看到土拨鼠！某些路段有很多岩石，穿防滑鞋！沿途有山间小屋可供休息，查看官方网站了解开放时间。| Summer blooms with alpine wildflowers, might even spot marmots! Some sections have many rocks, wear grippy shoes! Mountain huts available for rest along the way, check official website for opening hours.'
    },
    // Northern Italy trails
    {
        id: 11,
        name: 'Bellagio – Pescallo Loop',
        lat: 45.9886,
        lng: 9.2603,
        distance: '4.5km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '混合湖岸和山坡路线，视角不断变化，俯瞰科莫湖经典的"Y形"湖面。清晨或傍晚光线最佳，相对人少。| Mixed lakeshore and hillside route with constantly changing perspectives, overlooking Lake Como\'s classic "Y-shaped" lake surface. Best light in early morning or evening, relatively fewer crowds.'
    },
    {
        id: 12,
        name: 'Varenna – Sentiero del Viandante',
        lat: 46.0100,
        lng: 9.2833,
        distance: '6.8km',
        duration: '2.5h',
        bestSeason: 'Best: Apr-Jun / Sep-Oct',
        region: 'italy',
        description: '中世纪朝圣级别的徒步路线，在石径、橄榄林和湖边村庄之间交替。历史氛围浓厚，非常适合慢节奏步行。| Medieval pilgrimage-level hiking route, alternating between stone paths, olive groves, and lakeside villages. Strong historical atmosphere, perfect for slow-paced walking.'
    },
    {
        id: 13,
        name: 'Greenway del Lago di Como',
        lat: 45.9833,
        lng: 9.2667,
        distance: '10km',
        duration: '3-4h',
        bestSeason: 'Year-round',
        region: 'italy',
        description: '连接多个湖边小镇的平缓步道，可以分段完成。沿途有花园、别墅和湖景，非常适合"无技术压力"的风景步行。| Gentle trail connecting multiple lakeside towns, can be done in sections. Features gardens, villas, and lake views throughout, perfect for "no-technical-pressure" scenic walking.'
    },
    {
        id: 14,
        name: 'Sirmione Peninsula Walk',
        lat: 45.4917,
        lng: 10.6083,
        distance: '5.2km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'italy',
        description: '沿着半岛步行到尽头的卡图洛洞穴遗址。水晶般清澈的水域，遗址与自然的完美结合。有风但视野开阔。| Walk along the peninsula to the Grotte di Catullo ruins at the end. Crystal clear waters, excellent combination of ruins and nature. Windy but with open vistas.'
    },
    {
        id: 15,
        name: 'Monte Baldo Panorama Trail',
        lat: 45.7167,
        lng: 10.8500,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'italy',
        description: '缆车直达1700米海拔，山脊徒步俯瞰整个加尔达湖。高山草甸+大尺度湖景，风很大，注意保暖。| Cable car directly to 1700m elevation, ridge hiking overlooking the entire Lake Garda. Alpine meadows + large-scale lake views, quite windy, dress warmly.'
    },
    {
        id: 16,
        name: 'Riva del Garda – Ponale Path',
        lat: 45.8833,
        lng: 10.8500,
        distance: '8km',
        duration: '2.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '经典的悬崖边湖景路线，碎石路但技术难度低。湖水颜色变化非常明显，适合摄影。| Classic cliffside lake route, gravel path but low technical difficulty. Lake water color changes are very noticeable, photography-friendly.'
    },
    {
        id: 17,
        name: 'Isola Bella & Stresa Lakeside Walk',
        lat: 45.8833,
        lng: 8.5333,
        distance: '4km',
        duration: '1-1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '湖边步行+岛屿花园组合，人工与自然界限清晰。整体氛围优雅安静。| Lakeside walk + island garden combination, clear boundary between man-made and natural. Overall atmosphere is elegant and quiet.'
    },
    {
        id: 18,
        name: 'Monte Isola Loop',
        lat: 45.7167,
        lng: 10.0833,
        distance: '9km',
        duration: '3h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '环湖中央岛屿徒步，几乎没有机动车，村庄规模很小，当地生活氛围浓厚。湖区最不"过度旅游化"的地方之一。| Hiking around the lake\'s central island, almost no motor vehicles, very small village scale, strong local life atmosphere. One of the least "over-touristed" spots in the lake region.'
    },
    {
        id: 63,
        name: 'Lake Orta – San Giulio Island Walk',
        lat: 45.8167,
        lng: 8.4000,
        distance: '5km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '最安静的意大利湖区之一，小岛上有中世纪修道院。湖岸步道平缓，整体氛围宁静优雅，游客相对较少。| One of Italy\'s quietest lake regions, medieval monastery on small island. Gentle lakeside trail, overall atmosphere peaceful and elegant, relatively fewer tourists.'
    },
    {
        id: 64,
        name: 'Limone sul Garda – Limonaia Trail',
        lat: 45.8167,
        lng: 10.7833,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '沿着柠檬园和橄榄园的步道，俯瞰加尔达湖。历史悠久的柠檬种植传统，色彩丰富，适合轻松漫步。| Trail along lemon and olive groves, overlooking Lake Garda. Historic lemon cultivation tradition, rich colors, perfect for leisurely stroll.'
    },
    {
        id: 65,
        name: 'Malcesine – Monte Baldo Cable Car Walk',
        lat: 45.7667,
        lng: 10.8167,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'italy',
        description: '缆车直达山顶，然后沿山脊步道行走。360度湖景，高山植物丰富，风大但视野极佳。| Cable car to summit, then ridge trail walk. 360-degree lake views, rich alpine flora, windy but excellent vistas.'
    },
    {
        id: 66,
        name: 'Cannobio Lakeside Promenade',
        lat: 46.0667,
        lng: 8.7000,
        distance: '3km',
        duration: '1h',
        bestSeason: 'Year-round',
        region: 'italy',
        description: '马焦雷湖北端的优雅步道，连接历史中心与自然湖岸。适合傍晚散步，光线柔和，氛围浪漫。| Elegant promenade at Lake Maggiore\'s northern end, connecting historic center with natural lakeshore. Perfect for evening stroll, soft light, romantic atmosphere.'
    },
    {
        id: 67,
        name: 'Tremezzo – Villa Carlotta Gardens Walk',
        lat: 45.9833,
        lng: 9.2167,
        distance: '4.5km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'italy',
        description: '沿着科莫湖岸，经过著名别墅花园。人工与自然完美结合，春季杜鹃花盛开时尤其美丽。| Along Lake Como shore, passing famous villa gardens. Perfect blend of man-made and natural, especially beautiful when rhododendrons bloom in spring.'
    },
    // Dolomites trails
    {
        id: 19,
        name: 'Tre Cime di Lavaredo Loop',
        lat: 46.6189,
        lng: 12.3025,
        distance: '10.2km',
        duration: '3-4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '多洛米蒂最标志性的石灰岩山峰，成熟的环线步道，路标清晰。近距离体验垂直岩壁和碎石坡，风大且阳光强烈，记得防晒。| The most iconic limestone peaks of the Dolomites, mature loop trail with clear signage. Experience vertical rock walls and scree slopes up close, windy with strong sun exposure, remember sun protection.'
    },
    {
        id: 20,
        name: 'Lago di Braies',
        lat: 46.6942,
        lng: 12.0847,
        distance: '3.6km',
        duration: '1-1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'dolomites',
        description: '绿松石蓝色的湖泊+针叶林+悬崖倒影，清晨人最少。可以环湖步行或短暂停留拍照，商业化程度高但视觉震撼。| Turquoise blue lake + coniferous forests + cliff reflections, fewest people in early morning. Can walk around the lake or stop briefly for photos, heavily commercialized but visually stunning.'
    },
    {
        id: 21,
        name: 'Seceda Ridgeline',
        lat: 46.5500,
        lng: 11.7000,
        distance: '6.5km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '缆车直达高海拔，沿着刀锋般的草坡行走，景深感知极强。暴露的小径但技术难度不高，天气变化快，注意查看云层覆盖情况。| Cable car directly to elevation, walking along knife-edge grassy slopes with extreme depth perception. Exposed path but not technically difficult, weather changes quickly, check cloud coverage.'
    },
    {
        id: 22,
        name: 'Alpe di Siusi Loop',
        lat: 46.5333,
        lng: 11.6667,
        distance: '12km',
        duration: '4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '欧洲最大的高山草甸，平缓起伏的高地，远处是锯齿状的岩石山峰。非常适合慢行、摄影和放松，夏季到处是牛群。| Europe\'s largest alpine meadow, gentle rolling highland with jagged rock peaks in the distance. Perfect for slow walking, photography, and relaxation, cattle everywhere in summer.'
    },
    {
        id: 23,
        name: 'Passo Giau – Mondeval Walk',
        lat: 46.4833,
        lng: 12.0500,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '从山口开始，全景视野，层叠的山脊营造出极强的封闭感。光线变化非常戏剧性，日落时分尤其壮观。| Starting from the pass with panoramic views, layered ridges create an extremely enclosed feeling. Light changes are very dramatic, especially stunning during sunset hours.'
    },
    {
        id: 24,
        name: 'Cinque Torri',
        lat: 46.5167,
        lng: 12.0500,
        distance: '5.4km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '巨大的岩石塔矗立在草坡上，一战遗址散布各处。路线短但空间张力强，非常适合半日游。| Massive rock towers standing in grassy slopes, WWI ruins scattered throughout. Short route but strong spatial tension, perfect for half-day trip.'
    },
    {
        id: 25,
        name: 'Val di Funes – Odle Panorama Trail',
        lat: 46.6500,
        lng: 11.6833,
        distance: '7.8km',
        duration: '2.5-3h',
        bestSeason: 'Best: May-Oct',
        region: 'dolomites',
        description: '经典的"教堂+尖峰"画面山谷，牧场和岩壁比例优美。安静的村庄，整体节奏非常缓慢。| Classic "church + spires" picture valley, beautiful proportions of pastures and rock walls. Quiet villages, overall very slow-paced.'
    },
    {
        id: 26,
        name: 'Lago di Sorapis',
        lat: 46.5500,
        lng: 12.2167,
        distance: '11km',
        duration: '4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '目的地是乳蓝色的冰川湖，颜色极其不真实。某些路段有钢索辅助，小段暴露但无技术难度，雨后很滑。| Destination is a milky blue glacial lake, color is extremely unreal. Some sections have steel cable assistance, small exposed sections but not technical, slippery after rain.'
    },
    {
        id: 68,
        name: 'Lago di Carezza',
        lat: 46.4167,
        lng: 11.5833,
        distance: '1.5km',
        duration: '0.5h',
        bestSeason: 'Best: May-Oct',
        region: 'dolomites',
        description: '小巧但色彩极美的湖泊，被森林环绕，倒映拉特马尔山脉。短途环湖步道，非常适合拍照和短暂停留。| Small but extremely colorful lake, surrounded by forests, reflecting Latemar mountains. Short loop trail, perfect for photography and brief stop.'
    },
    {
        id: 69,
        name: 'Passo Rolle Panorama Trail',
        lat: 46.3000,
        lng: 11.7833,
        distance: '7km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '从山口出发的高原步道，面向帕拉迪索山群。开阔的高山草甸，夏季野花盛开，视野极其开阔。| Highland trail starting from pass, facing Pale di San Martino group. Open alpine meadows, wildflowers in summer, extremely open vistas.'
    },
    {
        id: 70,
        name: 'Marmolada Glacier Viewpoint',
        lat: 46.4333,
        lng: 11.8500,
        distance: '5km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '多洛米蒂唯一的冰川，缆车可达观景点。冰川与岩石山峰的强烈对比，感受气候变化的影响。| Dolomites\' only glacier, cable car to viewpoint. Strong contrast between glacier and rock peaks, sense of climate change impact.'
    },
    {
        id: 71,
        name: 'Cortina d\'Ampezzo – Faloria Ridge Walk',
        lat: 46.5333,
        lng: 12.1333,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'dolomites',
        description: '从著名滑雪小镇出发，缆车上山后沿山脊行走。俯瞰阿姆佩佐山谷，多洛米蒂经典视角。| Starting from famous ski town, cable car up then ridge walk. Overlooking Ampezzo valley, classic Dolomites perspective.'
    },
    {
        id: 72,
        name: 'Lago di Fedaia Loop',
        lat: 46.4500,
        lng: 11.8667,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Best: Jun-Oct',
        region: 'dolomites',
        description: '人工水库但位置绝佳，正对马尔莫拉达山。平缓环湖步道，适合家庭出游，风景稳定。| Artificial reservoir but excellent location, facing Marmolada. Gentle loop trail, suitable for families, stable scenery.'
    },
    // Swiss Alps trails
    {
        id: 27,
        name: 'Five Lakes Walk',
        lat: 46.0167,
        lng: 7.7500,
        distance: '9.8km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '经典的马特洪峰观景路线，连接5个高山湖泊，晴天可以看到雪峰倒影。整体难度低，但游客密度高。| Classic Matterhorn viewpoint route, connecting 5 alpine lakes, can see snow peak reflections on sunny days. Overall low difficulty, but high tourist density.'
    },
    {
        id: 28,
        name: 'Gornergrat Panorama Trail',
        lat: 45.9833,
        lng: 7.7833,
        distance: '6.3km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '山地火车直达观景山脊，俯瞰冰川和多个4000米以上的雪峰。壮观的景色，几乎完全是"被观看"的体验。| Mountain train directly to viewing ridge, overlooking glaciers and multiple 4000m+ snow peaks. Grand vistas, almost entirely "being watched".'
    },
    {
        id: 29,
        name: 'Grindelwald First – Bachalpsee',
        lat: 46.6500,
        lng: 8.0333,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: '高山湖泊+草甸组合，成熟的步道，安全感强。好天气时湖面倒影非常稳定，清晰的摄影点。| Alpine lake + meadow combination, mature path with strong sense of safety. Lake reflections are very stable in good weather, clear photography spots.'
    },
    {
        id: 30,
        name: 'Eiger Trail',
        lat: 46.5833,
        lng: 8.0000,
        distance: '6.5km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '沿着艾格峰北壁行走，垂直的岩壁营造出极强的压迫感。路径清晰但心理尺度很大，适合不恐高的人。| Walking along the Eiger north face, vertical rock walls create extreme sense of oppression. Path is clear but psychological scale is large, suitable for those not afraid of heights.'
    },
    {
        id: 31,
        name: 'Oeschinensee Panorama Loop',
        lat: 46.5000,
        lng: 7.7167,
        distance: '7km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: '深蓝色的冰川湖，湖岸和高岩壁营造出强烈的封闭感。可以短途徒步或环湖，非常适合慢节奏的一天。| Glacial lake with deep blue color, strong sense of enclosure from lake shore and high rock walls. Can do short hike or loop around lake, perfect for a slower-paced day.'
    },
    {
        id: 32,
        name: 'Aletsch Glacier Viewpoint Trail',
        lat: 46.3833,
        lng: 8.0167,
        distance: '8-10km',
        duration: '3-4h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '俯瞰欧洲最大的冰川，规模极其宏大。路线本身不难，但"人类-地质"的对比非常直接。| Overlooking Europe\'s largest glacier, scale is extremely grand. Route itself is not difficult, but the "human-geology" contrast is very direct.'
    },
    {
        id: 33,
        name: 'Mürren – Grütschalp Walk',
        lat: 46.5667,
        lng: 7.9000,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: '沿着悬崖边缘的高海拔步道，面向雪朗峰群。村庄、瀑布和山壁形成极其稳定的风景构图。| High-altitude trail along cliff edge, facing Schilthorn peak group. Villages, waterfalls, and mountain walls form extremely stable scenic composition.'
    },
    {
        id: 34,
        name: 'Schynige Platte Panorama Trail',
        lat: 46.6500,
        lng: 7.8500,
        distance: '5.6km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '高山植物+远山湖景，可以同时看到图恩湖和布里恩茨湖。植物多样性高，节奏轻松。| Alpine plants + distant lake views, can see both Lake Thun and Lake Brienz simultaneously. High plant diversity, relaxed pace.'
    },
    {
        id: 35,
        name: 'Val Bregaglia – Soglio Walk',
        lat: 46.3333,
        lng: 9.5333,
        distance: '6-8km',
        duration: '2.5-3h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: '从石砌的山村进入山谷徒步，尺度突然收紧。人少，商业感弱，更有"生活化的阿尔卑斯"氛围。| From stone-built mountain village into valley hiking, scale suddenly tightens. Few people, weak commercial feel, more "lived-in Alps" atmosphere.'
    },
    {
        id: 36,
        name: 'Engadin Lakes Trail',
        lat: 46.4833,
        lng: 9.8333,
        distance: '11km',
        duration: '3.5h',
        bestSeason: 'Best: Jun-Oct',
        region: 'switzerland',
        description: '连接多个高地湖泊，光线干净，地形平缓。整体氛围理性克制，"高度管理的自然"。| Connecting multiple highland lakes, clean light and gentle terrain. Overall atmosphere is rational and restrained, "highly managed nature".'
    },
    {
        id: 73,
        name: 'Lauterbrunnen Valley Walk',
        lat: 46.5833,
        lng: 7.9000,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: '著名的72瀑布谷，垂直的岩壁和瀑布群。平缓的谷底步道，适合所有年龄，感受瀑布的力量。| Famous valley of 72 waterfalls, vertical cliffs and waterfall groups. Gentle valley floor trail, suitable for all ages, feel waterfall power.'
    },
    {
        id: 74,
        name: 'Zermatt – Matterhorn Glacier Paradise',
        lat: 45.9833,
        lng: 7.7500,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'switzerland',
        description: '缆车直达3883米，欧洲最高的缆车站。近距离观察冰川和马特洪峰，极端高海拔体验。| Cable car to 3883m, Europe\'s highest cable car station. Close-up glacier and Matterhorn views, extreme high-altitude experience.'
    },
    {
        id: 75,
        name: 'Lake Lucerne – Rigi Panorama Trail',
        lat: 47.0500,
        lng: 8.4833,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: May-Oct',
        region: 'switzerland',
        description: '从瑞吉山俯瞰卢塞恩湖全景，经典的山湖组合。成熟的步道系统，适合一日游，视野开阔。| Overlooking Lake Lucerne panorama from Rigi, classic mountain-lake combination. Mature trail system, perfect for day trip, open vistas.'
    },
    {
        id: 76,
        name: 'Appenzell – Säntis Summit Trail',
        lat: 47.2500,
        lng: 9.3333,
        distance: '6km',
        duration: '2.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'switzerland',
        description: '缆车上山后沿山脊步道，俯瞰博登湖和阿尔卑斯山。传统瑞士乡村氛围，人相对较少。| Cable car up then ridge trail, overlooking Lake Constance and Alps. Traditional Swiss village atmosphere, relatively fewer people.'
    },
    {
        id: 77,
        name: 'Jungfraujoch – Top of Europe Walk',
        lat: 46.5500,
        lng: 7.9833,
        distance: '3km',
        duration: '1h',
        bestSeason: 'Year-round',
        region: 'switzerland',
        description: '欧洲最高的火车站，3454米海拔。冰川步道和观景台，极端高海拔体验，需要适应。| Europe\'s highest railway station, 3454m elevation. Glacier trail and viewing platforms, extreme high-altitude experience, requires acclimatization.'
    },
    // Austrian Alps trails
    {
        id: 37,
        name: 'Hallstatt – Dachstein Panorama Walk',
        lat: 47.5622,
        lng: 13.6492,
        distance: '5.5km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '湖泊、盐矿小镇和陡峭的山壁层叠在同一画面中，景观密度极高。明显商业化，但地形和尺度非常典型。| Lake, salt mining town, and steep mountain walls layered in the same frame, extremely high landscape density. Clearly commercialized, but terrain and scale are very typical.'
    },
    {
        id: 38,
        name: 'Gosausee Loop',
        lat: 47.5333,
        lng: 13.5167,
        distance: '4.5km',
        duration: '1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '水晶般清澈的湖泊，晴天可以看到达赫斯坦冰川的倒影。短环线但视觉完整，非常适合作为轻量级自然景点。| Crystal clear lake, can see Dachstein glacier reflections on sunny days. Short loop route but visually complete, perfect as a lightweight nature spot.'
    },
    {
        id: 39,
        name: 'Salzkammergut Lakes Trail',
        lat: 47.7000,
        lng: 13.6167,
        distance: '8-12km',
        duration: '3-4h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '湖泊和森林交替，平缓的斜坡，整体节奏缓慢。"宜居的阿尔卑斯"，更注重生活氛围而非荒野。| Lakes and forests alternating, gentle slopes, overall slow pace. "Livable Alps", more about living atmosphere than wilderness.'
    },
    {
        id: 40,
        name: 'Krimml Waterfalls Path',
        lat: 47.2167,
        lng: 12.1833,
        distance: '4km',
        duration: '2h',
        bestSeason: 'Best: May-Sep',
        region: 'austria',
        description: '欧洲落差最大的瀑布群，水量极大，声音和湿度存在感强烈。奥地利最具"自然力量展示"的路线之一。| Europe\'s highest drop waterfall group, extremely high water volume, sound and humidity have strong presence. One of Austria\'s most "natural power display" routes.'
    },
    {
        id: 41,
        name: 'Grossglockner High Alpine Road Walks',
        lat: 47.0833,
        lng: 12.8333,
        distance: '6-10km',
        duration: '2-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: '沿高山公路的短途徒步组合，可以近距离观察冰川和裸露的岩石。宏大的自然尺度，但人类干预感明显。| Short hiking combinations along high alpine road, can observe glaciers and bare rock up close. Grand natural scale, but clear sense of human intervention.'
    },
    {
        id: 42,
        name: 'Zell am See – Schmittenhöhe Trail',
        lat: 47.3167,
        lng: 12.8000,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'austria',
        description: '湖泊和山坡之间视角转换清晰，俯瞰滨湖采尔全景。天气不稳定时非常适合灵活安排行程。| Clear perspective shifts between lake and hillside, overlooking Zell am See panorama. Perfect for flexible itinerary when weather is unstable.'
    },
    {
        id: 43,
        name: 'Hohe Tauern National Park Trail',
        lat: 47.1667,
        lng: 12.5000,
        distance: '10-15km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: '奥地利最大的国家公园，冰川、湿地和宽阔的山谷共存。开阔的空间，相对较少的人类干预，更接近"生态阿尔卑斯"。| Austria\'s largest national park, glaciers, wetlands, and wide valleys coexist. Open space, relatively less human intervention, closer to "ecological Alps".'
    },
    {
        id: 44,
        name: 'Rax Plateau Loop',
        lat: 47.7000,
        lng: 15.7000,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '高地高原地形，草甸和岩壁突然展开。非常适合从城市到山区的短途旅行，技术徒步要求低。| Highland plateau terrain, meadows and rock walls suddenly unfold. Perfect for short trips from city into mountains, low technical hiking requirements.'
    },
    {
        id: 45,
        name: 'Hochschwab Plateau Hike',
        lat: 47.6167,
        lng: 15.1500,
        distance: '12-18km',
        duration: '5-6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: '巨大的石灰岩高原，开阔的空间，方向感强。人少，路标稀疏，更适合有经验的徒步者。| Massive limestone plateau, open space with strong sense of direction. Few people, sparse trail markers, more suitable for experienced hikers.'
    },
    {
        id: 46,
        name: 'Wilder Kaiser Mountains Loop',
        lat: 47.5500,
        lng: 12.3000,
        distance: '9-13km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: '陡峭岩壁和牧场共存的区域，非常立体的山体。比多洛米蒂更"厚重"，但构图不那么戏剧性。| Area where steep rock walls and pastures coexist, very three-dimensional mountain mass. More "substantial" than Dolomites, but less dramatic composition.'
    },
    {
        id: 78,
        name: 'Innsbruck – Nordkette Cable Car Walk',
        lat: 47.2833,
        lng: 11.4000,
        distance: '5km',
        duration: '2h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '从因斯布鲁克市中心缆车直达山顶，俯瞰整个城市和因河谷。城市与自然的完美结合，交通便利。| Cable car from Innsbruck city center to summit, overlooking entire city and Inn valley. Perfect blend of city and nature, easily accessible.'
    },
    {
        id: 79,
        name: 'St. Anton – Verwall Valley Trail',
        lat: 47.1333,
        lng: 10.2667,
        distance: '10km',
        duration: '3.5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'austria',
        description: '从著名滑雪小镇进入山谷徒步，传统阿尔卑斯牧场氛围。人少安静，适合想要远离人群的徒步者。| Entering valley hike from famous ski town, traditional Alpine pasture atmosphere. Few people and quiet, suitable for hikers seeking solitude.'
    },
    {
        id: 80,
        name: 'Wörthersee Lakeside Trail',
        lat: 46.6167,
        lng: 14.2667,
        distance: '12km',
        duration: '3h',
        bestSeason: 'Best: Apr-Oct',
        region: 'austria',
        description: '奥地利最温暖的湖泊，湖岸步道连接多个小镇。适合轻松骑行或步行，夏季游泳很受欢迎。| Austria\'s warmest lake, lakeside trail connecting multiple towns. Perfect for leisurely cycling or walking, popular for swimming in summer.'
    },
    {
        id: 81,
        name: 'Bad Gastein – Waterfall Path',
        lat: 47.1167,
        lng: 13.1333,
        distance: '3km',
        duration: '1h',
        bestSeason: 'Year-round',
        region: 'austria',
        description: '温泉小镇的瀑布步道，历史悠久的度假胜地。短途但风景优美，结合了自然和历史建筑。| Waterfall trail in spa town, historic resort destination. Short but scenic, combining nature and historic architecture.'
    },
    {
        id: 82,
        name: 'Dachstein – Five Fingers Viewpoint',
        lat: 47.5167,
        lng: 13.6167,
        distance: '2km',
        duration: '1h',
        bestSeason: 'Best: May-Oct',
        region: 'austria',
        description: '缆车上山后步行到著名的"五指"观景台，悬挑在悬崖上。极端刺激的观景体验，需要不恐高。| Cable car up then walk to famous "Five Fingers" viewing platform, cantilevered over cliff. Extremely thrilling viewing experience, requires no fear of heights.'
    },
    // French Alps trails
    {
        id: 47,
        name: 'Lac Blanc',
        lat: 45.9833,
        lng: 6.8667,
        distance: '6km',
        duration: '2.5-3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: '经典的高山湖泊路线，俯瞰勃朗峰山体，晴天湖面可以反射雪峰轮廓。游客很多，但构图极其稳定。| Classic alpine lake route overlooking Mont Blanc massif, lake surface can reflect snow peak outlines on sunny days. Many tourists, but composition is extremely stable.'
    },
    {
        id: 48,
        name: 'Grand Balcon Nord',
        lat: 45.9167,
        lng: 6.8667,
        distance: '7.5km',
        duration: '3h',
        bestSeason: 'Best: Jun-Oct',
        region: 'france',
        description: '沿着山坡穿越霞慕尼山谷，面向完整的勃朗峰山体。成熟的路线，坡度适中，一条"精心设计的观景步道"。| Traversing Chamonix valley along mountainside, facing complete Mont Blanc massif. Mature route with moderate slopes, a "precisely designed viewing trail".'
    },
    {
        id: 49,
        name: 'Mer de Glace Viewpoint Walk',
        lat: 45.9333,
        lng: 6.9167,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'france',
        description: '冰川退缩后地质结构的特写视图，对比极其强烈。不算"美丽"，但时间和尺度的感知非常直接。| Close-up view of geological structures after glacier retreat, extremely strong contrast. Not "beautiful", but direct sense of time and scale.'
    },
    {
        id: 50,
        name: 'Aiguille du Midi Ridge Area',
        lat: 45.9000,
        lng: 6.8833,
        distance: '3-4km',
        duration: '1-1.5h',
        bestSeason: 'Year-round (weather dependent)',
        region: 'france',
        description: '缆车直达3800米海拔，极端的垂直感和暴露的视野共存。更像是一个体验点而非完整的徒步路线。| Cable car directly to 3800m elevation, extreme vertical sense and exposed views coexist. More of an experience point than a complete hike.'
    },
    {
        id: 51,
        name: 'Lake Annecy – Talloires Walk',
        lat: 45.8500,
        lng: 6.1667,
        distance: '8km',
        duration: '3h',
        bestSeason: 'Best: Apr-Oct',
        region: 'france',
        description: '湖岸和山坡平行，水体与城市边界非常清晰。整体氛围更接近"宜居景观"而非纯阿尔卑斯。| Lakeshore and hillside parallel, water body and city boundaries very clear. Overall atmosphere closer to "livable landscape" than pure alpine.'
    },
    {
        id: 52,
        name: 'Vanoise National Park Trail',
        lat: 45.3333,
        lng: 6.8333,
        distance: '10-15km',
        duration: '4-6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: '法国最早的国家公园之一，冰川山谷和高山牧场共存。比瑞士更野性，设施比奥地利少。| One of France\'s earliest national parks, glacial valleys and alpine pastures coexist. Wilder than Switzerland, less facilities than Austria.'
    },
    {
        id: 53,
        name: 'Queyras Regional Nature Park Loop',
        lat: 44.7000,
        lng: 6.8000,
        distance: '9-12km',
        duration: '4-5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: '靠近意大利边境的高山地区，人少，地形干燥。色彩偏灰绿，整体更粗糙和边缘化。| High mountain area near Italian border, few people, dry terrain. Colors lean gray-green, overall more rough and marginal.'
    },
    {
        id: 54,
        name: 'Val d\'Isère Alpine Meadow Walk',
        lat: 45.4500,
        lng: 6.9833,
        distance: '7km',
        duration: '3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: '滑雪区在夏季转变为高山草甸，开阔且平缓起伏。"功能性山地"转变为徒步空间的典型例子。| Ski area transforms into alpine meadows in summer, open and gently rolling. Typical example of "functional mountain" converted to hiking space.'
    },
    {
        id: 88,
        name: 'Chamonix – Petit Balcon Sud',
        lat: 45.9167,
        lng: 6.8667,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: Jun-Sep',
        region: 'france',
        description: '霞慕尼南侧的小阳台步道，面向勃朗峰。比大阳台更安静，适合想要避开人群的徒步者。| Small balcony trail on Chamonix south side, facing Mont Blanc. Quieter than Grand Balcon, suitable for hikers seeking fewer crowds.'
    },
    {
        id: 89,
        name: 'Lake Geneva – Évian-les-Bains Promenade',
        lat: 46.4000,
        lng: 6.5833,
        distance: '5km',
        duration: '1.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'france',
        description: '日内瓦湖法国一侧的优雅步道，经过著名温泉小镇。湖光山色，适合轻松漫步，氛围优雅。| Elegant promenade on French side of Lake Geneva, passing famous spa town. Lake and mountain views, perfect for leisurely stroll, elegant atmosphere.'
    },
    {
        id: 90,
        name: 'Grenoble – Bastille Hill Walk',
        lat: 45.1833,
        lng: 5.7167,
        distance: '3km',
        duration: '1h',
        bestSeason: 'Year-round',
        region: 'france',
        description: '从城市中心到堡垒的短途步道，俯瞰格勒诺布尔和周围山脉。城市与自然的结合，交通便利。| Short trail from city center to fortress, overlooking Grenoble and surrounding mountains. Blend of city and nature, easily accessible.'
    },
    {
        id: 91,
        name: 'Les Deux Alpes – Glacier Walk',
        lat: 45.0167,
        lng: 6.1333,
        distance: '4km',
        duration: '1.5h',
        bestSeason: 'Year-round',
        region: 'france',
        description: '夏季滑雪胜地的冰川步道，高海拔体验。可以近距离观察冰川，感受高山的极端环境。| Glacier trail in summer ski resort, high-altitude experience. Can observe glaciers up close, feel extreme alpine environment.'
    },
    // German Alps trails
    {
        id: 55,
        name: 'Zugspitze Summit Area',
        lat: 47.4211,
        lng: 10.9853,
        distance: '6–8km',
        duration: '2.5–3h',
        bestSeason: 'Best: Jun-Sep',
        region: 'germany',
        description: '德国最高峰，可缆车直达。视野横跨德奥边境，山体尺度不如瑞士但象征意义极强，人工设施感明显。| Germany\'s highest peak, accessible by cable car. Views span the German-Austrian border, mountain scale less impressive than Switzerland but highly symbolic, strong sense of artificial facilities.'
    },
    {
        id: 56,
        name: 'Partnach Gorge',
        lat: 47.4833,
        lng: 11.1167,
        distance: '2.5km',
        duration: '1–1.5h',
        bestSeason: 'Year-round',
        region: 'germany',
        description: '狭窄峡谷、湍急水流与隧道式步道，非常贴近身体尺度。短程但感官密度高，适合轻量自然体验。| Narrow gorge, rushing waters and tunnel-like pathways, very close to human scale. Short distance but high sensory density, perfect for lightweight nature experience.'
    },
    {
        id: 57,
        name: 'Mittenwald – Karwendel Panorama Trail',
        lat: 47.4333,
        lng: 11.2667,
        distance: '8–10km',
        duration: '3–4h',
        bestSeason: 'Best: Jun-Oct',
        region: 'germany',
        description: '从彩绘小镇进入 Karwendel 山脉，森林转为开阔草坡。整体气质安静、生活化，人少于楚格峰区域。| Entering Karwendel mountains from painted town, forests transition to open grassy slopes. Overall atmosphere quiet and lived-in, fewer people than Zugspitze area.'
    },
    {
        id: 58,
        name: 'Eibsee Loop',
        lat: 47.4500,
        lng: 10.9833,
        distance: '7.5km',
        duration: '2–2.5h',
        bestSeason: 'Year-round',
        region: 'germany',
        description: '湖水清澈，正对楚格峰北壁。路线平缓、完成度极高，是"德国式秩序自然"的代表。| Crystal clear lake facing Zugspitze north face. Gentle route with extremely high completion, representative of "German ordered nature".'
    },
    {
        id: 59,
        name: 'Watzmann East Face View Trail',
        lat: 47.5500,
        lng: 12.9333,
        distance: '8–12km',
        duration: '4–5h',
        bestSeason: 'Best: Jun-Sep',
        region: 'germany',
        description: '德国最具存在感的山体之一，东壁极具压迫感。徒步本身不难，但空间尺度明显严肃。| One of Germany\'s most imposing mountains, east face extremely oppressive. Hiking itself not difficult, but spatial scale clearly serious.'
    },
    {
        id: 60,
        name: 'Königssee – Obersee Walk',
        lat: 47.5667,
        lng: 12.9833,
        distance: '5–7km',
        duration: '2–3h',
        bestSeason: 'Best: May-Oct',
        region: 'germany',
        description: '峡谷型湖泊，湖岸几乎垂直。需乘船进入，之后步行到 Obersee，景观极端"完成"。| Gorge-type lake with nearly vertical shores. Requires boat access, then walk to Obersee, landscape extremely "complete".'
    },
    {
        id: 61,
        name: 'Alpsee & Neuschwanstein Foothills',
        lat: 47.5576,
        lng: 10.7494,
        distance: '6km',
        duration: '2h',
        bestSeason: 'Best: Apr-Oct',
        region: 'germany',
        description: '城堡脚下的湖泊与森林步道，历史叙事强于自然野性，但构图稳定、易进入。| Lake and forest trails at castle foothills, historical narrative stronger than natural wildness, but composition stable and easily accessible.'
    },
    {
        id: 62,
        name: 'Berchtesgaden National Park Trail',
        lat: 47.6333,
        lng: 13.0000,
        distance: '10–15km',
        duration: '4–6h',
        bestSeason: 'Best: Jun-Sep',
        region: 'germany',
        description: '德国唯一的阿尔卑斯国家公园，湖泊、湿地、林线变化明显。自然保护强度高，人为干预相对少。| Germany\'s only Alpine national park, lakes, wetlands and treeline changes are obvious. High nature protection intensity, relatively less human intervention.'
    },
    {
        id: 83,
        name: 'Garmisch-Partenkirchen – Partnachklamm Extended',
        lat: 47.4833,
        lng: 11.1167,
        distance: '6km',
        duration: '2.5h',
        bestSeason: 'Year-round',
        region: 'germany',
        description: '帕特纳赫峡谷的延伸路线，从峡谷到高山草甸。路线变化丰富，从狭窄到开阔，体验完整。| Extended route from Partnach Gorge, from gorge to alpine meadows. Rich route variation, from narrow to open, complete experience.'
    },
    {
        id: 84,
        name: 'Tegernsee Loop',
        lat: 47.7000,
        lng: 11.7500,
        distance: '9km',
        duration: '2.5h',
        bestSeason: 'Best: Apr-Oct',
        region: 'germany',
        description: '慕尼黑附近的优雅湖泊，环湖步道平缓。传统巴伐利亚度假氛围，适合家庭出游，设施完善。| Elegant lake near Munich, gentle loop trail. Traditional Bavarian resort atmosphere, suitable for families, well-equipped.'
    },
    {
        id: 85,
        name: 'Schliersee – Spitzingsee Trail',
        lat: 47.7167,
        lng: 11.8667,
        distance: '8km',
        duration: '2.5h',
        bestSeason: 'Best: May-Oct',
        region: 'germany',
        description: '连接两个高山湖泊的步道，穿过森林和草甸。相对安静的区域，游客较少，自然氛围浓厚。| Trail connecting two alpine lakes, through forests and meadows. Relatively quiet area, fewer tourists, strong natural atmosphere.'
    },
    {
        id: 86,
        name: 'Ramsau – Hintersee Loop',
        lat: 47.6167,
        lng: 12.9000,
        distance: '5km',
        duration: '1.5h',
        bestSeason: 'Best: May-Oct',
        region: 'germany',
        description: '贝希特斯加登附近的小湖，正对瓦茨曼山。短途环湖步道，风景如画，适合轻松漫步。| Small lake near Berchtesgaden, facing Watzmann. Short loop trail, picturesque scenery, perfect for leisurely stroll.'
    },
    {
        id: 87,
        name: 'Füssen – Forggensee Lakeside',
        lat: 47.5667,
        lng: 10.7000,
        distance: '7km',
        duration: '2h',
        bestSeason: 'Best: Apr-Oct',
        region: 'germany',
        description: '新天鹅堡附近的人工湖，湖岸步道连接多个景点。结合历史与自然，适合一日游安排。| Artificial lake near Neuschwanstein, lakeside trail connecting multiple attractions. Combining history and nature, perfect for day trip planning.'
    }
    ],
    pyrenees: [
        // Southern France trails
        {
            id: 100,
            name: 'Cirque de Gavarnie',
            lat: 42.7333,
            lng: -0.0167,
            distance: '6km',
            duration: '2h',
            bestSeason: 'Best: Jun-Sep',
            region: 'france-south',
            description: '世界遗产的天然圆形剧场，423米高的瀑布从悬崖倾泻而下。从村庄出发的轻松步道，面向雄伟的岩壁。| UNESCO World Heritage natural amphitheater, 423m waterfall cascading from cliffs. Easy trail from village, facing majestic rock walls.'
        },
        {
            id: 101,
            name: 'Pic du Midi de Bigorre',
            lat: 43.0667,
            lng: 0.1500,
            distance: '4km',
            duration: '1.5h',
            bestSeason: 'Best: Jun-Sep',
            region: 'france-south',
            description: '缆车直达2877米，著名的天文台所在地。360度比利牛斯山脉全景，极端高海拔体验。| Cable car to 2877m, famous observatory location. 360-degree Pyrenees panorama, extreme high-altitude experience.'
        },
        {
            id: 102,
            name: 'Lac de Gaube',
            lat: 42.8500,
            lng: -0.1167,
            distance: '8km',
            duration: '2.5h',
            bestSeason: 'Best: Jun-Oct',
            region: 'france-south',
            description: '高山湖泊，正对维涅马勒峰。从卡泰雷特出发的步道，穿过森林到达清澈的湖泊。| Alpine lake facing Vignemale peak. Trail from Cauterets, through forests to crystal clear lake.'
        },
        {
            id: 103,
            name: 'Pont d\'Espagne – Lac de Gaube',
            lat: 42.8667,
            lng: -0.1167,
            distance: '5km',
            duration: '1.5h',
            bestSeason: 'Best: May-Oct',
            region: 'france-south',
            description: '从历史石桥到高山湖泊的经典路线。瀑布、森林和湖泊的组合，适合所有年龄。| Classic route from historic stone bridge to alpine lake. Combination of waterfalls, forests and lakes, suitable for all ages.'
        },
        {
            id: 104,
            name: 'Col du Tourmalet – Pic du Midi',
            lat: 42.9167,
            lng: 0.1500,
            distance: '10km',
            duration: '4h',
            bestSeason: 'Best: Jun-Sep',
            region: 'france-south',
            description: '从著名的环法自行车赛山口出发，徒步到皮克杜米迪。高海拔步道，视野极其开阔。| Starting from famous Tour de France pass, hike to Pic du Midi. High-altitude trail, extremely open vistas.'
        },
        {
            id: 105,
            name: 'Gorges de Kakuetta',
            lat: 43.1167,
            lng: -0.8833,
            distance: '3km',
            duration: '1.5h',
            bestSeason: 'Best: Apr-Oct',
            region: 'france-south',
            description: '狭窄的石灰岩峡谷，有栈道和瀑布。巴斯克地区的自然奇观，短途但感官密度高。| Narrow limestone gorge with boardwalks and waterfalls. Natural wonder in Basque Country, short but high sensory density.'
        },
        {
            id: 106,
            name: 'Lac d\'Artouste',
            lat: 42.8667,
            lng: -0.4000,
            distance: '6km',
            duration: '2h',
            bestSeason: 'Best: Jun-Sep',
            region: 'france-south',
            description: '高山小火车到达的湖泊，海拔2000米。人工湖但位置绝佳，周围是原始的高山景观。| Lake reached by mountain train, 2000m elevation. Artificial but excellent location, surrounded by pristine alpine scenery.'
        },
        // Spanish Pyrenees trails
        {
            id: 200,
            name: 'Ordesa y Monte Perdido National Park',
            lat: 42.6500,
            lng: -0.0333,
            distance: '12km',
            duration: '4h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '西班牙最古老的国家公园之一，奥德萨峡谷令人惊叹。垂直的岩壁和瀑布，世界遗产地。| One of Spain\'s oldest national parks, Ordesa Canyon is stunning. Vertical cliffs and waterfalls, UNESCO World Heritage site.'
        },
        {
            id: 201,
            name: 'Aigüestortes i Estany de Sant Maurici',
            lat: 42.5833,
            lng: 0.9333,
            distance: '10km',
            duration: '3.5h',
            bestSeason: 'Best: Jun-Oct',
            region: 'spain',
            description: '加泰罗尼亚唯一的国家公园，200多个高山湖泊。冰川景观，适合多日徒步。| Catalonia\'s only national park, over 200 alpine lakes. Glacial landscapes, suitable for multi-day hiking.'
        },
        {
            id: 202,
            name: 'Valle de Tena – Ibón de Piedrafita',
            lat: 42.7167,
            lng: -0.3167,
            distance: '8km',
            duration: '2.5h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '从特纳谷到高山湖泊的步道。传统阿拉贡村庄，进入原始高山环境。| Trail from Tena Valley to alpine lake. Traditional Aragon villages, entering pristine alpine environment.'
        },
        {
            id: 203,
            name: 'Camino de Santiago – Pyrenees Section',
            lat: 42.8333,
            lng: -1.0000,
            distance: '15km',
            duration: '5h',
            bestSeason: 'Best: May-Oct',
            region: 'spain',
            description: '著名的朝圣之路在比利牛斯山的部分。历史与自然结合，文化意义深远。| Famous pilgrimage route through Pyrenees. Combining history and nature, profound cultural significance.'
        },
        {
            id: 204,
            name: 'Panticosa – Ibones de Bachimaña',
            lat: 42.7333,
            lng: -0.2833,
            distance: '9km',
            duration: '3h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '从温泉小镇到高山湖泊群。传统比利牛斯山村庄氛围，进入原始高山环境。| From spa town to alpine lake group. Traditional Pyrenees village atmosphere, entering pristine alpine environment.'
        },
        {
            id: 205,
            name: 'Valle de Ansó – Selva de Oza',
            lat: 42.8333,
            lng: -0.8333,
            distance: '11km',
            duration: '4h',
            bestSeason: 'Best: Jun-Oct',
            region: 'spain',
            description: '保存完好的山谷，原始森林和传统建筑。相对较少游客，体验传统比利牛斯山生活。| Well-preserved valley, pristine forests and traditional architecture. Relatively fewer tourists, experience traditional Pyrenees life.'
        },
        {
            id: 206,
            name: 'Parque Natural de la Sierra y Cañones de Guara',
            lat: 42.3167,
            lng: -0.2000,
            distance: '8km',
            duration: '3h',
            bestSeason: 'Best: Apr-Oct',
            region: 'spain',
            description: '阿拉贡的天然公园，以峡谷和洞穴闻名。地中海气候影响，植被独特。| Aragon natural park, famous for canyons and caves. Mediterranean climate influence, unique vegetation.'
        },
        {
            id: 207,
            name: 'Montserrat – Sant Jeroni Summit',
            lat: 41.6000,
            lng: 1.8333,
            distance: '6km',
            duration: '2.5h',
            bestSeason: 'Year-round',
            region: 'spain',
            description: '加泰罗尼亚的圣山，独特的锯齿状岩峰。从修道院出发的步道，文化意义深远。| Catalonia\'s holy mountain, unique jagged rock peaks. Trail from monastery, profound cultural significance.'
        },
        {
            id: 208,
            name: 'Sierra Nevada – Mulhacén Summit Trail',
            lat: 37.0500,
            lng: -3.3167,
            distance: '18km',
            duration: '8h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '伊比利亚半岛最高峰（3479米），从阿尔普哈拉斯山谷出发。高难度路线，需要经验和准备，但视野极其壮观。| Highest peak in Iberian Peninsula (3479m), starting from Alpujarras valley. Challenging route requiring experience and preparation, but extremely spectacular views.'
        },
        {
            id: 209,
            name: 'Sierra Nevada – Laguna de Aguas Verdes',
            lat: 37.0833,
            lng: -3.3000,
            distance: '12km',
            duration: '5h',
            bestSeason: 'Best: Jun-Oct',
            region: 'spain',
            description: '内华达山脉的高山湖泊，海拔3000米以上。冰川形成的湖泊，周围是裸露的岩石山峰，景观原始。| Alpine lake in Sierra Nevada, over 3000m elevation. Glacial-formed lake, surrounded by bare rock peaks, pristine landscape.'
        },
        {
            id: 210,
            name: 'Picos de Europa – Ruta del Cares',
            lat: 43.1833,
            lng: -4.8333,
            distance: '12km',
            duration: '4h',
            bestSeason: 'Best: May-Oct',
            region: 'spain',
            description: '欧洲之巅最著名的路线，沿着卡雷斯河峡谷。部分路段在岩壁上开凿，工程壮观，风景绝美。| Most famous route in Picos de Europa, along Cares River gorge. Some sections carved into rock walls, spectacular engineering, stunning scenery.'
        },
        {
            id: 211,
            name: 'Picos de Europa – Naranjo de Bulnes',
            lat: 43.2000,
            lng: -4.8167,
            distance: '14km',
            duration: '6h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '西班牙最著名的攀岩山峰之一，从乌尔迪昂出发的观景路线。石灰岩山峰，垂直岩壁极具视觉冲击。| One of Spain\'s most famous climbing peaks, viewing route from Urriellu. Limestone peak, vertical rock walls extremely visually striking.'
        },
        {
            id: 212,
            name: 'Picos de Europa – Lagos de Covadonga',
            lat: 43.2667,
            lng: -5.0167,
            distance: '6km',
            duration: '2h',
            bestSeason: 'Best: Jun-Oct',
            region: 'spain',
            description: '两个冰川湖泊，海拔1100米。从科瓦东加出发的轻松步道，适合所有年龄，风景如画。| Two glacial lakes, 1100m elevation. Easy trail from Covadonga, suitable for all ages, picturesque scenery.'
        },
        {
            id: 213,
            name: 'Sierra de Guadarrama – Peñalara Summit',
            lat: 40.8500,
            lng: -3.9667,
            distance: '10km',
            duration: '4h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '瓜达拉马山脉最高峰（2428米），距离马德里仅一小时。高山湖泊和草甸，适合一日游。| Highest peak in Sierra de Guadarrama (2428m), only one hour from Madrid. Alpine lakes and meadows, perfect for day trip.'
        },
        {
            id: 214,
            name: 'Sierra de Gredos – Circo de Gredos',
            lat: 40.2500,
            lng: -5.3000,
            distance: '14km',
            duration: '5h',
            bestSeason: 'Best: Jun-Sep',
            region: 'spain',
            description: '格雷多斯山脉的冰川圆形剧场，多个高山湖泊。花岗岩山峰，景观原始，人相对较少。| Glacial amphitheater in Sierra de Gredos, multiple alpine lakes. Granite peaks, pristine landscape, relatively fewer people.'
        },
        {
            id: 215,
            name: 'Cabo de Gata – Playa de los Genoveses',
            lat: 36.8333,
            lng: -2.0833,
            distance: '8km',
            duration: '2.5h',
            bestSeason: 'Best: Oct-Apr',
            region: 'spain',
            description: '安达卢西亚的自然公园，火山地貌和原始海滩。地中海气候，冬季最佳，夏季太热。| Natural park in Andalusia, volcanic landscape and pristine beaches. Mediterranean climate, best in winter, too hot in summer.'
        },
        {
            id: 216,
            name: 'Sierra de Cazorla – Río Borosa Trail',
            lat: 38.0833,
            lng: -2.8333,
            distance: '10km',
            duration: '3.5h',
            bestSeason: 'Best: Apr-Jun / Sep-Nov',
            region: 'spain',
            description: '西班牙最大的自然公园，沿着博罗萨河的步道。瀑布、峡谷和森林，生物多样性丰富。| Spain\'s largest natural park, trail along Borosa River. Waterfalls, gorges and forests, rich biodiversity.'
        },
        {
            id: 217,
            name: 'Parque Natural de los Alcornocales',
            lat: 36.3333,
            lng: -5.5833,
            distance: '12km',
            duration: '4h',
            bestSeason: 'Best: Oct-May',
            region: 'spain',
            description: '欧洲最大的软木橡树林，地中海森林生态系统。相对平坦的步道，适合轻松徒步，鸟类丰富。| Europe\'s largest cork oak forest, Mediterranean forest ecosystem. Relatively flat trails, suitable for easy hiking, rich birdlife.'
        },
        {
            id: 218,
            name: 'Sierra de Grazalema – Garganta Verde',
            lat: 36.7500,
            lng: -5.3667,
            distance: '6km',
            duration: '2.5h',
            bestSeason: 'Best: Oct-May',
            region: 'spain',
            description: '安达卢西亚的石灰岩山脉，狭窄的绿色峡谷。需要提前预约，保护严格，自然原始。| Limestone mountains in Andalusia, narrow green gorge. Requires advance booking, strict protection, pristine nature.'
        },
        {
            id: 219,
            name: 'Islas Cíes – Monte Faro Trail',
            lat: 42.2167,
            lng: -8.9000,
            distance: '5km',
            duration: '2h',
            bestSeason: 'Best: May-Sep',
            region: 'spain',
            description: '加利西亚海岸的岛屿，需要乘船到达。从海滩到山顶的步道，大西洋全景，被誉为"大西洋的加勒比"。| Islands off Galicia coast, requires boat access. Trail from beach to summit, Atlantic panorama, known as "Caribbean of the Atlantic".'
        },
        {
            id: 220,
            name: 'Parque Natural de la Albufera',
            lat: 39.3333,
            lng: -0.3500,
            distance: '8km',
            duration: '2.5h',
            bestSeason: 'Year-round',
            region: 'spain',
            description: '瓦伦西亚附近的湿地公园，重要的候鸟栖息地。平缓的步道，适合观鸟，结合了自然和文化。| Wetland park near Valencia, important migratory bird habitat. Gentle trails, perfect for birdwatching, combining nature and culture.'
        },
        {
            id: 221,
            name: 'Sierra de Tramuntana – Torrent de Pareis',
            lat: 39.8333,
            lng: 2.8167,
            distance: '7km',
            duration: '3h',
            bestSeason: 'Best: Apr-Jun / Sep-Oct',
            region: 'spain',
            description: '马略卡岛的世界遗产山脉，狭窄的峡谷和清澈的水池。需要一定技术，但风景独特，地中海岛屿特色。| UNESCO World Heritage mountains in Mallorca, narrow gorge and clear pools. Requires some technique, but unique scenery, Mediterranean island character.'
        },
        {
            id: 222,
            name: 'Parque Nacional de las Tablas de Daimiel',
            lat: 39.1500,
            lng: -3.7000,
            distance: '4km',
            duration: '1.5h',
            bestSeason: 'Best: Oct-Apr',
            region: 'spain',
            description: '拉曼查地区的湿地公园，重要的鸟类保护区。木板步道，适合观鸟，冬季最佳，夏季可能干涸。| Wetland park in La Mancha, important bird sanctuary. Boardwalk trails, perfect for birdwatching, best in winter, may dry in summer.'
        }
    ]
};

// Current series
let currentSeries = 'alpine';

// Get current locations based on selected series
function getCurrentLocations() {
    return seriesData[currentSeries] || [];
}